apiVersion: v1
kind: Pod
metadata:
  name: dns-debug
  labels:
    app: dns-debug
spec:
  containers:
  - name: dnsutils
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
  restartPolicy: Never
