name: terraform-secure

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - name: Init
        run: terraform -chdir=modules/B_mock_exam/exam_04/starter/terraform init -backend=false
      - name: Fmt
        run: terraform -chdir=modules/B_mock_exam/exam_04/starter/terraform fmt -check
      - name: Validate
        run: terraform -chdir=modules/B_mock_exam/exam_04/starter/terraform validate
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: modules/B_mock_exam/exam_04/starter/terraform
