name: supply-chain-scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build image
        run: docker build -t app:ci .
      - name: Secret scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect -v
      - name: SAST (Semgrep)
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
      - name: SBOM + vuln scan (Trivy)
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: app:ci
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
