name: ci-basic

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Lint
        run: pylint app.py
      - name: Test
        run: pytest -q
      - name: Build artifact
        run: tar czf app.tar.gz app.py
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.tar.gz
