apiVersion: v1
kind: LimitRange
metadata:
  name: lr-demo
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 1
      memory: 512Mi
    min:
      cpu: 50m
      memory: 64Mi
