name: log-pipeline-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: log-processor
      IMAGE_TAG: ${{ github.sha }}
      REGISTRY: ghcr.io/your-org
      DOCKERFILE: modules/B_mock_exam/exam_02/starter/Dockerfile
      CONTEXT: modules/B_mock_exam/exam_02/starter
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run tests (if present)
      run: |
        set -euo pipefail
        shopt -s nullglob
        tests=(modules/B_mock_exam/exam_02/starter/*tests.py)
        if [ ${#tests[@]} -gt 0 ]; then
          for t in "${tests[@]}"; do
            echo "Running $t"
            python "$t"
          done
        else
          echo "No tests found."
        fi

    - name: Build Docker image
      run: |
        set -euo pipefail
        IMAGE="${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
        docker build -f "${DOCKERFILE}" -t "${IMAGE}" "${CONTEXT}"
        echo "Built ${IMAGE}"

    - name: Push Docker image (placeholder)
      env:
        REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      run: |
        set -euo pipefail
        if [ -z "${REGISTRY_TOKEN:-}" ]; then
          echo "No registry token configured; skipping push."
          exit 0
        fi
        echo "${REGISTRY_TOKEN}" | docker login "${REGISTRY}" -u "${{ github.actor }}" --password-stdin
        IMAGE="${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
        docker push "${IMAGE}"
